### ISSUE TITLE
Error in using marginal effect functions

### ISSUE THREAD

**Issue by PCK1992** [sduxbury/ergMargins#1]
When I try to run the functions on a simple ergm I get the following error:

```
ergm.mma(model0a)
Error in xergm.common::adjust(nw.k, nw.j, remove = FALSE, value = 1, returnlabels = TRUE) : 
  At t = 1, there are 103 duplicate target column names.
```

The only function that works for is `vif.ergm(model0a)` . xergm package is installed and everything up to date. In my estimation, I only loaded the statnet and this library.

**Comment by sduxbury** [comment]
Can you send along the code you are using? Just a hunch, but the ergm.mma function requires two models and the names of two model terms to work. All functions other than vif.ergm require character strings identifying the variables of interest, which might be why vif.ergm is the only one working if you are not calling out specific variables to use. An example, ergm.mma should be,

ergm.mma(model1,model2,direct="avariable",mediator="anothervariable").

ergm.MEM and ergm.AME similarly need at least,

ergm.MEM(model,var1="avariable") 
ergm.AME(model,var1="avariable").

There are more examples in the help files for the ergMargins package that might be helpful. Let me know if that works! Otherwise, send along a reproducible example and I will look into it.

**Comment by PCK1992** [comment]
I misinterpreted the documentation - my bad! I will close this issue.
